services:
  supermarket:
    build: .
    image: supermarket-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://10.0.132.158:3306/supermarket?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ADDRESS: 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
