user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {

    upstream supermarket_app {
        server 10.0.141.223:8080 max_fails=3 fail_timeout=10s;
        server 10.0.134.49:8080 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;
        server_name _;

        # Healthcheck do Load Balancer
        location /healthcheck {
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        # Proxy para a aplicação Java
        location / {
            proxy_pass http://supermarket_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
