events {}

http {
    server {
        listen 80;

        # Página inicial (opcional)
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Swagger UI
        location /swagger-ui/ {
            proxy_pass http://supermarket:8080/swagger-ui/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            try_files $uri $uri/ /swagger-ui/index.html;
        }

        # API Docs (SEM barra no final)
        location /v3/api-docs {
            proxy_pass http://supermarket:8080/v3/api-docs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Swagger Config
        location /v3/api-docs/swagger-config {
            proxy_pass http://supermarket:8080/v3/api-docs/swagger-config;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Suas APIs REST
        location /api/ {
            proxy_pass http://supermarket:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
